CREATE TABLE IF NOT EXISTS mpa
(
    id   LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    id           LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    release_date DATE CHECK (release_date > '1895-12-28'),
    duration     INTEGER CHECK (duration > 0),
    mpa_id       LONG REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  LONG NOT NULL REFERENCES films (id),
    genre_id LONG NOT NULL REFERENCES genres (id),
    CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR NOT NULL UNIQUE,
    login    VARCHAR NOT NULL UNIQUE,
    name     VARCHAR NOT NULL,
    birthday DATE    NOT NULL
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id LONG NOT NULL REFERENCES films (id),
    user_id LONG NOT NULL REFERENCES users (id),
    CONSTRAINT pk_film_likes PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendships
(
    from_user_id LONG NOT NULL REFERENCES users (id),
    to_user_id   LONG NOT NULL REFERENCES users (id),
    accepted     BOOLEAN NOT NULL,
    CONSTRAINT pk_friendships PRIMARY KEY (from_user_id, to_user_id)
);